// calling the meetupForm
// sending async json data to the Db from the local folder generated by end user.

import Head from "next/head";

import { Fragment } from "react";
import NewMeetupForm from "../NewMeetupForm";

const NewmeetUp = () => {
  async function addMeetUpHandler(meetupData) {
    const responce = await fetch("/api/new-meetup", {
      method: "POST",
      body: JSON.stringify(meetupData),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data = await responce.json();

    console.log(data);
  }

  return (
    <Fragment>
      <Head>
        <title>Register your Company</title>
        <meta
          name="description"
          content="Please register your company profile here"
        />
      </Head>

      <NewMeetupForm onAddMeetup={addMeetUpHandler} />
    </Fragment>
  );
};
export default NewmeetUp;
